module.exports = [ 
//Weihnachtslieder 1
{ data: { text: 'Weihnachtslieder - Track1? Fülle aus:', mp3: 'mp3/xmasSongs/Frage1.mp3', options: ['Name des Lieds', 'Melodieinstrument'], category: 'Weihnachtslieder'}, correct_text: ['Leise rieselt der Schnee', 'Oboe'], time_limit: 1, answerType: 3 },
{ data: { text: 'Weihnachtslieder - Track2? Fülle aus:', mp3: 'mp3/xmasSongs/Frage3.mp3', options: ['Name des Lieds', 'Melodieinstrument'], category: 'Weihnachtslieder'}, correct_text: ['Vom Himmel hoch da komm ich her', 'Trompete'], time_limit: 1, answerType: 3 },
{ data: { text: 'Weihnachtslieder - Track3? Fülle aus:', mp3: 'mp3/xmasSongs/Frage4.mp3', options: ['Name des Lieds', 'Melodieinstrument'], category: 'Weihnachtslieder'}, correct_text: ['Süßer die Glocken nie klingen', 'Zither'], time_limit: 1, answerType: 3 },
{ data: { text: 'Weihnachtslieder - Track4? Fülle aus:', mp3: 'mp3/xmasSongs/Frage5.mp3', options: ['Name des Lieds', 'Melodieinstrument'], category: 'Weihnachtslieder'}, correct_text: ['Macht hoch die Tür die Tor macht weit', 'Panflöte'], time_limit: 1, answerType: 3 },
{ data: { text: 'Weihnachtslieder - Track5? Fülle aus:', mp3: 'mp3/xmasSongs/Frage6.mp3', options: ['Name des Lieds', 'Melodieinstrument'], category: 'Weihnachtslieder'}, correct_text: ['Es wird scho glei dumpa', 'Alphorn'], time_limit: 1, answerType: 3 },
//Dubbi
{ data: { text: 'Der Flughafen BER wurde am 04.11.2020 offiziell in Betrieb genommen. Welcher war KEINER der Baumängel während der Bauphase?', options: ['1036 Bäume wurden falsch gepflanzt und mussten umgesetzt werden.', 'Einige Treppengeländer waren unvollständig. Es fehlten bis zu 5m.', 'Beim Bau des Parkhauses wurden Kabelschächte vergessen.', '2 der Landebahnen waren ursprünglich rund 50m zu nah aneinander.'], category: '2020 Time by Dubbi'}, correct_id: 3, time_limit: 1, answerType: 1 },
{ data: { text: 'Der Urlaub war von diesem Lied geprägt. Doch wann stand Blinding Lights von The Weeknd erstmals auf Platz 1 der deutschen Single Charts?', options: ['03.12.2019', '10.01.2020', '28.04.2020', '17.05.2020'], category: '2020 Time by Dubbi'}, correct_id: 1, time_limit: 1, answerType: 1 },
{ data: { text: 'Wie oft wurde ein Tweet von Trump in der ersten Woche nach der Wahl als falsch oder irreführend markiert?',  image: 'img/trumpTwitter.jpg',  options: [], category: '2020 Time by Dubbi'}, correct_id: 31, time_limit: 1, answerType: 2},
{ data: { text: 'Wie viel Geld konnte “THE NAKED PHILANTHROPIST” geschätzt in der ersten Woche nach Ihrem Spendenaufruf mit Nacktbildern für die Bekämpfung der australischen Buschfeuer sammeln? (in $)',  image: 'img/girl.jpg',  options: [], category: '2020 Time by Dubbi'}, correct_id: 700000, time_limit: 1, answerType: 2},
//Andy B
{ data: { text: 'Welches Ereignis fand an diesem Ort im Jahr 2020 statt?',  image: 'img/fourseasons.jpg',  options: ['Größter Chemieskandal der US-Geschichte', 'Pressekonferenz von Rudy Giuliani zum angeblichen Wahlbetrug', 'Trump hielt eine Rede zu seinem Impeachment verfahren', 'Der benachbarte Buchladen für Erwachsene wollte die Hallen kaufen und fand dort unterschlagene Wahlunterlagen'], category: '2020 Time by Andy B.'}, correct_id: 1, time_limit: 1, answerType: 1, answerImage: 'img/fourseasons2.jpg'},
{ data: { text: 'Folgendes Video: Film oder Real?', mp4: 'mp4/blade.mp4', options: ['Film', 'Real'], category: '2020 Time by Andy B.'}, correct_id: 1, time_limit: 1, answerType: 1},
{ data: { text: 'Der Name des Babys von Elon Musk sorgte für Kontroversen. Doch wie heist das Kind eigentlich (laut dem ersten Tweet nach der Geburt)?', image: 'img/elon.jpg', options: ['Name'], category: '2020 Time by Andy B.'}, correct_text: ['X AE A-12'], time_limit: 1, answerType: 3, answerImage: 'img/elon2.jpg' },
{ data: { text: 'Im September began ein Post von Dwayne TheRock Johnson mit "Not my finest hour...". Was war vorher passiert?', options: ['Sein Tochter hat ihm Make-Over verpasst, welches nach hinten los ging.', 'Er hat sein Gartentor händisch zerstört weil es nicht auf ging', 'Bei einem Autounfall zerstörte er mehrere Fahrräder', 'Nach einem Streit mit Vin Diesel zeigte er Einsicht und entschuldigt sich'], category: '2020 Time by Andy B.'}, correct_id: 1, time_limit: 1, answerType: 1, answerImage: 'img/rock.png' },
{ data: { text: 'Wer wird auf diesem Meme angeschrien?', image: 'img/xc.jpg', options: ['?'], category: 'Meme Time by Andy B.'}, correct_text: ['Katze'], time_limit: 1, answerType: 3, answerImage: 'img/cat2.jpg'},
{ data: { text: 'Wie wird der Mann auf dem Meme genannt?', image: 'img/x.jpg', options: ['Joe', 'Hugo', 'Harold', 'Bernard'], category: 'Meme Time by Andy B.'}, correct_id: 2, time_limit: 1, answerType: 1 },
// Chris Xmas trivia
{ data: { text: 'Seit wann gibt es den heute üblichen Adventskranz?', options: ['1925', '1825', '1725', '1625'], category: 'Christaaaaaaaans Weihnachts-Trivia'}, correct_id: 0, time_limit: 1, answerType: 1 },
{ data: { text: 'Warum wird bei den Amerikanern Weihnachten auch „Xmas“ genannt?', options: ['Klang cooler für die schwarze Community und hat sich so eingebürgert', 'Lässt sich schneller und einfacher schreiben', 'Kommt aus einer anderen Sprache', 'Ist aus einer Werbeaktion entstanden'], category: 'Christaaaaaaaans Weihnachts-Trivia'}, correct_id: 2, time_limit: 1, answerType: 1 },
{ data: { text: 'Welche dieser regionalen Plätzchensorten gibt es nicht?', options: ['Coburger Schmätzchen', 'Viechtacher Bärenmanndn', 'Dettelbacher Muskatzinen', 'Badener Chräbeli'], category: 'Christaaaaaaaans Weihnachts-Trivia'}, correct_id: 1, time_limit: 1, answerType: 1 },
{ data: { text: 'Um wieviel Prozent änderte sich 2019 am Abend des 24.12. die amerikanische Nutzung von Pornhub?', options: ['+5%', '-8%', '+22%', '-35%'], category: 'Christaaaaaaaans Weihnachts-Trivia'}, correct_id: 0, time_limit: 1, answerType: 1, answerImage: 'https://cs.phncdn.com/insights-static/wp-content/uploads/2019/12/5-pornhub-insights-2019-year-review-holidays-united-states.png'},
// Simon und Jojo
{ data: { text: 'Wie oft haben wir zusammengerechnet schon besoffen ins Bett gekotzt?', options: ['0 mal', '4 mal', '7 mal', '9 mal'], category: 'The Big \'Johannes Schregle und Simon Johannes Gloger\' Quiz'}, correct_id: 1, time_limit: 1, answerType: 1},
{ data: { text: 'Was hat Simon bereits im Suff beim Sturz vom Fahrrad in die Hecke gesagt?', options: ['„Die Hecke ist weich ich bleibe hier!“', '„Scheiße, da ist was mitgekommen!“', '„Kickdown-Start ist nicht gut für den ADAC!“', '„Stepbro, I am stuck!“'], category: 'The Big \'Johannes Schregle und Simon Johannes Gloger\' Quiz'}, correct_id: 2, time_limit: 1, answerType: 1},
{ data: { text: 'Wie viel sind unsere CSGO Inventare zusammengerechnet wert? (Stand: 15.12.2020)', options: ['70,45€', '124,55€', '144,32€', '167,86€'], category: 'The Big \'Johannes Schregle und Simon Johannes Gloger\' Quiz'}, correct_id: 1, time_limit: 1, answerType: 1},
{ data: { text: 'In welchen Fächern waren wir beide im Gymnasium schlecht?', options: ['Deutsch', 'Sport', 'Chemie', 'Kunst'], category: 'The Big \'Johannes Schregle und Simon Johannes Gloger\' Quiz'}, correct_id: 2, time_limit: 1, answerType: 1},
{ data: { text: 'Welches Ereignis ist NICHT auf unserer Abifahrt passiert?', options: ['Jojo hat im Arm drücken gegen Frau Bock verloren', 'Simon hat ins Meer geschissen', 'Jojo hat zwischen hunderten Touristen in eine Tüte gekotzt', 'Simon hat im Bus in eine Fortunaflasche gepisst'], category: 'The Big \'Johannes Schregle und Simon Johannes Gloger\' Quiz'}, correct_id: 0, time_limit: 1, answerType: 1},
{ data: { text: 'Wann hat Simon das Dampfen angefangen?', options: ['Dezember 2016', 'Oktober 2017', 'April 2018', 'Mai 2019'], category: 'The Big \'Johannes Schregle und Simon Johannes Gloger\' Quiz'}, correct_id: 3, time_limit: 1, answerType: 1},
{ data: { text: 'Wann hat Jojo das Dampfen angefangen?', options: ['Dezember 2016', 'Oktober 2017', 'April 2018', 'März 2019'], category: 'The Big \'Johannes Schregle und Simon Johannes Gloger\' Quiz'}, correct_id: 1, time_limit: 1, answerType: 1},
{ data: { text: 'Wie viele Sexpartner haben wir zusammen schon gehabt?', options: ['8', '10', '11,5', '12'], category: 'The Big \'Johannes Schregle und Simon Johannes Gloger\' Quiz'}, correct_id: 0, time_limit: 1, answerType: 1},
{ data: { text: 'Wann haben wir unser erstes Handy bekommen?', options: ['3. Klasse', '4. Klasse', '5. Klasse', '6. Klasse'], category: 'The Big \'Johannes Schregle und Simon Johannes Gloger\' Quiz'}, correct_id: 0, time_limit: 1, answerType: 1},
{ data: { text: 'Seit wann gibt es den Partykeller in Aystetten?', options: ['14. August 2016', '21. November 2016', '19. April 2017', '26. November 2017'], category: 'The Big \'Johannes Schregle und Simon Johannes Gloger\' Quiz'}, correct_id: 3, time_limit: 1, answerType: 1},
{ data: { text: 'Welche Sportart hat noch keiner von uns in einem Verein ausgeübt?', options: ['Schwimmen', 'Tischtennis', 'Skifahren', 'Leichtathletik'], category: 'The Big \'Johannes Schregle und Simon Johannes Gloger\' Quiz'}, correct_id: 2, time_limit: 1, answerType: 1},
// Trump Tweets
{ data: { text: 'Ist folgender Tweet von Trump echt oder fake?', image: 'img/tweets/TrumpTweet9.webp', options: ['Echt', 'Fake'], category: 'Real or Fake - Die Trump Tweets'}, correct_id: 0, time_limit: 1, answerType: 1},
{ data: { text: 'Ist folgender Tweet von Trump echt oder fake?', image: 'img/tweets/TrumpTweet8.webp', options: ['Echt', 'Fake'], category: 'Real or Fake - Die Trump Tweets'}, correct_id: 1, time_limit: 1, answerType: 1},
{ data: { text: 'Ist folgender Tweet von Trump echt oder fake?', image: 'img/tweets/TrumpTweet1.webp', options: ['Echt', 'Fake'], category: 'Real or Fake - Die Trump Tweets'}, correct_id: 1, time_limit: 1, answerType: 1},
{ data: { text: 'Ist folgender Tweet von Trump echt oder fake?', image: 'img/tweets/TrumpTweet11.webp', options: ['Echt', 'Fake'], category: 'Real or Fake - Die Trump Tweets'}, correct_id: 0, time_limit: 1, answerType: 1},
{ data: { text: 'Ist folgender Tweet von Trump echt oder fake?', image: 'img/tweets/TrumpTweet12.webp', options: ['Echt', 'Fake'], category: 'Real or Fake - Die Trump Tweets'}, correct_id: 1, time_limit: 1, answerType: 1},
//Weihnachtslieder 2
{ data: { text: 'Weihnachtslieder - Track6? Fülle aus:', mp3: 'mp3/xmasSongs/Frage7.mp3', options: ['Name des Lieds', 'Melodieinstrument'], category: 'Weihnachtslieder'}, correct_text: ['Maria durch ein Dornwald ging', 'Gitarre'], time_limit: 1, answerType: 3 },
{ data: { text: 'Weihnachtslieder - Track7? Fülle aus:', mp3: 'mp3/xmasSongs/Frage8.mp3', options: ['Name des Lieds', 'Melodieinstrument'], category: 'Weihnachtslieder'}, correct_text: ['Gloria in excelsis deo', 'Geige'], time_limit: 1, answerType: 3 },
{ data: { text: 'Weihnachtslieder - Track8? Fülle aus:', mp3: 'mp3/xmasSongs/Frage9.mp3', options: ['Name des Lieds', 'Melodieinstrument'], category: 'Weihnachtslieder'}, correct_text: ['Tochter Zion', 'Orgel'], time_limit: 1, answerType: 3 },
{ data: { text: 'Weihnachtslieder - Track9? Fülle aus:', mp3: 'mp3/xmasSongs/Frage2.mp3', options: ['Name des Lieds', 'Melodieinstrument'], category: 'Weihnachtslieder'}, correct_text: ['Stille Nacht', 'Fagott'], time_limit: 1, answerType: 3 },
]