module.exports = [
     // Allgemeinwissen
     { data: { text: 'In welchem Land war der Pro-Kopf-Konsum von Bier weltweit am höchsten? (2018)', options: ['Polen', 'Deutschland', 'Tschechien', 'England'] }, correct_id: 2, time_limit: 1 },  
     { data: { text: 'In welchem Land gibt es die meisten Pyramieden', options: ['Sudan', 'Australien', 'Äqypten', 'Indonesien'] }, correct_id: 0, time_limit: 1 },  
     { data: { text: 'Was ist der Weltrekord für den längsten Schluckauf (in Jahren)?', options: []}, correct_id: 69, time_limit: 1 },
     { data: { text: 'Welches Unternehmen hatte für einen kurzen Zeitpunkt einmal das 6. größte Militär der Welt?', options: ['Heckler und Koch', 'Pepsi', 'Black Rock', 'Lego'] }, correct_id: 1, time_limit: 1 },  
     { data: { text: 'Welche dieser Personen saß für die CSU im Bundestag?', options: ['Gaius Octavius', 'Albert Uderzo', 'Josef Stalin', 'Cajus Julius Caesar'] }, correct_id: 3, time_limit: 1 },  
     { data: { text: 'Sortiere nach Kicktipp Gesammtpunkten? (meiste --> wenigste) (Stand 6.8.20 16:45 Uhr)',  options: ['Lena',  'Hoerby', 'Thommy', 'Andy'], order: [2, 3, 0, 1] }, correct_id: 0, time_limit: 1},
     { data: { text: 'Aus welchem Jahr stammt der älteste Film?', options: ['1914', '1888', '1857', '1904'] }, correct_id: 1, time_limit: 1 },  
     { data: { text: 'Wer verwandelte eine seiner Romanfiguren in ein riesiges Ungeziefer?', options: ['Gottfried Keller', 'Friedrich Schiller', 'Franz Kafka', 'Thomas Mann'] }, correct_id: 2, time_limit: 1 },  
     { data: { text: 'Welches dieser US-Teams gibt es nicht?', options: ['Dallas Dodgers', 'Dallas Stars', 'Dallas Maveriks', 'Dallas Cowboys'] }, correct_id: 0, time_limit: 1 },  
     { data: { text: 'Ordne folgende Künstler nach verkauften Tonträgern! (meiste --> wenigste) ',  options: ['Eminem',  'Madonna', 'The Beatles', 'Queen'], order: [2, 1, 0, 3] }, correct_id: 0, time_limit: 1},
     // 187 - Tom
     { data: { text: '"One Eight Seven", 187, ist der sogenannte Ten Code der amerikanischen Polizei für?', image: 'img/a0.jpg', options: ['Drogendelikte', 'Prostitution', 'Geldwäsche', 'Mord'] }, correct_id: 3, time_limit: 1 },                                                                                                                                         
     { data: { text: 'Wie viele Milliliter SpeziE muss man trinken um auf 187g Zucker zu kommen? (auf ganze Milliliter gerundet)', image: 'img/a1.jpg', options: []}, correct_id: 1558, time_limit: 1 },
     { data: { text: 'Welchen 187 Straßenbande Shisha Tabak gibt es nicht?', image: 'img/a2.jpg', options: ['Papa Candy', 'Beach Vibes', 'Red Light District', 'Flying Hirsch'] }, correct_id: 0, time_limit: 1 },                                                                                                                                         
     { data: { text: '187 war insgeammt 76 Wochen in den Charts. Wie lange saßen ihre Mitglieder zusammengerechnet im Knast? (in Wochen)', image: 'img/a3.jpg', options: []}, correct_id: 270, time_limit: 1 },
     { data: { text: 'Welches Kennzeichen hat der CL500 von GZUZ?', image: 'img/a4.jpg', options: ['B-GZ-187', 'HH-XL-187', 'AC-AB-187', 'GZ-UZ-187'] }, correct_id: 1, time_limit: 1 },         
     { data: { text: 'Welcher dieser Personen ist nicht Teil der Straßenbande?', image: 'img/a5.jpg', options: ['A', 'B', 'C', 'D'] }, correct_id: 0, time_limit: 1 },  
     { data: { text: 'Wer ist der 187. Bundesliga Torschütze des FC Augsburg gewesen?', image: 'img/a6.jpg', options: ['Ja-choel Koo', 'Caiuby', 'Dominik Kohr', 'Alfred Finnbogasson'] }, correct_id: 0, time_limit: 1 },     
     { data: { text: 'Wie viele Tore fielen in den ersten 187 Minuten der Halbfinalserie \'Augsburger Panther - EHC Red Bull München\'?', image: 'img/a7.jpg', options: []}, correct_id: 10, time_limit: 1 },
     { data: { text: 'In wie vielen Spielen des FC Bayern Basketball wurden mehr als 187 Punkte erreicht? (21 Spiele)?', image: 'img/a8.jpg', options: ['A', 'B', 'C', 'D'] }, correct_id: 0, time_limit: 1 }, 
     { data: { text: 'Wie viele montaliche Hörer erreicht 187 auf Spotify (Stand 4.6.20 20Uhr)', options: []}, correct_id: 830123, time_limit: 1 },
     { data: { text: 'Welche dieser Serien erreichte die 187. Folge?', image: 'img/a9.jpg', options: ['Game of Thrones', 'Gossip Girl', 'Modern Family', 'The Mentalist'] }, correct_id: 2, time_limit: 1 },  
     { data: { text: 'Wie viele Isotpe mit der Massenzahl (Protonen + Neutronen) 187 gibt es?', options: ['10', '4', '7', '12'] }, correct_id: 3, time_limit: 1 },  
     { data: { text: 'Was geschah am 18.7.1898?', options: ['Tomas Edison gelang die erste Tonaufzecihnung', 'Die Curies stellten das Polonium vor', 'Die erste Dampflock fährt von Nürnberg nach Fürth', 'Weimarer Republik wird ausgerufen'] }, correct_id: 1, time_limit: 1 },  
     { data: { text: 'Wie viel Euro sind 187 Kroatische Kuna?', options: ['78,43', '102,94', '185,55', '24,72'] }, correct_id: 3, time_limit: 1 },  
     { data: { text: 'Wann hatte die Adidas-Aktie das letze mal einen Wert unter 187€', image: 'img/a10.jpg', options: ['März 2020', 'März 2019', 'März 2018', 'März 2017'] }, correct_id: 0, time_limit: 1 },  
     { data: { text: 'In welchen Bundesländern liegt die B187?', image: 'img/a11.jpg', options: ['Brandenburg und Berlin', 'Sachsen-Anhalt und Brandenburg', 'Sachsen-Anhalt und Tühringen', 'Sachsen und Tühringen'] }, correct_id: 1, time_limit: 1 },  
     { data: { text: 'Welche dieser Staßen hat eine Hausnummer 187?', options: ['Maximillian Str.', 'Rosenau Str.', 'Bürgermeister Ackermann Str.', 'Haunstetter Str.'] }, correct_id: 3, time_limit: 1 },  
     { data: { text: 'Welchen %-Anteil an der Weltbevölkerung hat das 187. Land (St. Lucia)?', options: ['0,002', '0,001', '0,05', '0,01'] }, correct_id: 0, time_limit: 1 },  
     { data: { text: 'Welche Stadt hatte um das Jahr 1870 die meisten Einwohner?', options: ['London', 'New York', 'Paris', 'Peking'] }, correct_id: 0, time_limit: 1 },  
     { data: { text: 'Welche dieser Postleitzahlen gehört zum Hamburger Bezirk St. Pauli', image: 'img/a11.jpg', options: ['20111', '20187', '20299', '20355'] }, correct_id: 3, time_limit: 1 },  
     // Simon Memorial Questions
     { data: { text: 'Welche dieser Aussagen zum Vapen ist falsch?', options: ['Beim Vapen wird kein Nikotin eingeatmet', 'In Bayern ist das Vapen ist in Gaststätten erlaubt', 'Es gibt keine Passivvapen', 'Beim Gebrauch werden Zigaretten heißer als das Liquid'] }, correct_id: 0, time_limit: 1 },  
     { data: { text: 'Wie viele Bundesländer hat Deuschland?', options: []}, correct_id: 16, time_limit: 1 },  
     { data: { text: 'Wie viele Abonnenten hat der YT Kanal Pietsmiet (Stand 4.6.20 21:20Uhr, in Mio.)', options: ['1,8', '2,0', '2,4', '2,9'] }, correct_id: 2, time_limit: 1 },  
     { data: { text: 'Welcher dieser Champs wurde als letztes zu LoL hinzugefügt?', options: ['Yuumi', 'Qiyana', 'Sett', 'Aphelios'] }, correct_id: 2, time_limit: 1 },  
     { data: { text: 'Welchen dieser Burger gab es noch nie be McDonalds?', options: ['PietSmiet Burger', 'McDouble Hanf ', 'Homestyle Crispy Chicken', 'Greek Mac'] }, correct_id: 1, time_limit: 1 }, 
     // 50/50
     { data: { text: 'Welche Partei in den USA stellte mehr Präsidenten?', options: ['Repuplikaner', 'Demokraten'] }, correct_id: 0, time_limit: 1 },  
     { data: { text: 'Wer hat mehr Instagram-Follower?', options: ['fe24x', 'chrissy.365'] }, correct_id: 0, time_limit: 1 },  
     { data: { text: 'Was kam zuerst?', options: ['Streichholz', 'Feuerzeug'] }, correct_id: 1, time_limit: 1 },  
     { data: { text: 'Welches Land ist flächenmäßig am größten?', image: 'img/a12.jpg', options: ['Deutschland', 'Italien'] }, correct_id: 0, time_limit: 1 },  
     { data: { text: 'Astronauten können im Weltall rülpsen?', image: 'img/a13.jpg', options: ['Wahr', 'Falsch'] }, correct_id: 1, time_limit: 1 },  
]