module.exports = [ 

{ data: { text: 'Der Flughafen BER wurde am 04.11.2020 offiziell in Betrieb genommen. Welcher war KEINER der Baumängel während der Bauphase?', options: ['1036 Bäume wurden falsch gepflanzt und mussten umgesetzt werden.', 'Einige Treppengeländer waren unvollständig. Es fehlten bis zu 5m.', 'Beim Bau des Parkhauses wurden Kabelschächte vergessen.', '2 der Landebahnen waren ursprünglich rund 50m zu nah aneinander.'], category: '2020 Time by Dubbi'}, correct_id: 3, time_limit: 1, answerType: 1 },
{ data: { text: 'Wann stand Blinding Lights von The Weeknd erstmals auf Platz 1 der deutschen Single Charts?', options: ['03.12.2019', '10.01.2020', '28.04.2020', '17.05.2020'], category: '2020 Time by Dubbi'}, correct_id: 1, time_limit: 1, answerType: 1 },
{ data: { text: 'Wie oft wurde ein Tweet von Trump in der ersten Woche nach der Wahl als falsch oder irreführend markiert?',  image: 'img/trumpTwitter.jpg',  options: [], category: '2020 Time by Dubbi'}, correct_id: 31, time_limit: 1, answerType: 2},
{ data: { text: 'Wie viel Geld konnte “THE NAKED PHILANTHROPIST” geschätzt in der ersten Woche nach Ihrem Spendenaufruf mit Nacktbildern für die Bekämpfung der australischen Buschfeuer sammeln? (in $)',  image: 'media/img/girl.jpg',  options: [], category: '2020 Time by Dubbi'}, correct_id: 700000, time_limit: 1, answerType: 2},
{ data: { text: 'Welches Ereignis fand an diesem Ort im Jahr 2020 statt?',  image: 'media/img/fourseasons.jpg',  options: ['Größter Chemieskandal der US-Geschichte', 'Pressekonferenz von Rudy Giuliani zum angeblichen Wahlbetrug', 'Trump hielt eine Rede zu seinem Impeachment verfahren', 'Der benachbarte Buchladen für Erwachsene wollte die Hallen kaufen und fand dort unterschlagene Wahlunterlagen'], category: '2020 Time by Andy B.'}, correct_id: 1, time_limit: 1, answerType: 1, answerImage: 'media/img/fourseasons2.jpg'},
{ data: { text: 'Folgendes Video: Film oder Real?', mp4: 'media/mp4/blade.mp4', options: ['Film', 'Real'], category: '2020 Time by Andy B.'}, correct_id: 1, time_limit: 1, answerType: 1},
{ data: { text: 'Der Name des Babys von Elon Musk sorgte für Kontroversen. Doch wie heist das Kind eigentlich (laut dem ersten Tweet nach der Geburt)?', image: 'media/img/elon.jpg', options: ['Name'], category: '2020 Time by Andy B.'}, correct_text: ['X AE A-12'], time_limit: 1, answerType: 3, answerImage: 'media/img/elon2.jpg' },
{ data: { text: 'Im September began ein Post von Dwayne TheRock Johnson mit "Not my finest hour...". Was war vorher passiert?', options: ['Sein Tochter hat ihm Make-Over verpasst, welches nach hinten los ging.', 'Er hat sein Gartentor händisch zerstört weil es nicht auf ging', 'Bei einem Autounfall zerstörte er mehrere Fahrräder', 'Nach einem Streit mit Vin Diesel zeigte er Einsicht und entschuldigt sich'], category: '2020 Time by Andy B.'}, correct_id: 1, time_limit: 1, answerType: 1, answerImage: 'media/img/rock.png' },
{ data: { text: 'Wer wird auf diesem Meme angeschrien?', image: 'media/img/xc.jpg', options: ['?'], category: 'Meme Time by Andy B.'}, correct_text: ['Katze'], time_limit: 1, answerType: 3, answerImage: 'media/img/cat2.jpg'},
{ data: { text: 'Wie wird der Mann auf dem Meme genannt?', image: 'media/img/x.jpg', options: ['Joe', 'Hugo', 'Harold', 'Bernard'], category: 'Meme Time by Andy B.'}, correct_id: 2, time_limit: 1, answerType: 1 }

]