module.exports = [ 
{ data: { text: 'Der Alligator hat im Tierreich die stärkste Bisskraft',  options: ['Wahr', 'Falsch'] }, correct_id: 1, time_limit: 1},
{ data: { text: 'Bayern hat ca. 13 Milliionen Einwohner und ist damit das bevölkerungsreichste Bundesland Deutschlands',  options: ['Wahr', 'Falsch'] }, correct_id: 1, time_limit: 1},
{ data: { text: 'Rotkäppchen bringt im gleichnamigen Märchen der Gebrüder Grimm ihrer Großmutter eine Flasche Wein und Kekse',  options: ['Wahr', 'Falsch'] }, correct_id: 1, time_limit: 1},
{ data: { text: 'Bis zu 3.000 Menschen erkranken jährlich an der Pest',  options: ['Wahr', 'Falsch'] }, correct_id: 0, time_limit: 1},
{ data: { text: 'Nach dem Tod wachsen Haare und Fingernägel weiter',  options: ['Wahr', 'Falsch'] }, correct_id: 1, time_limit: 1},
{ data: { text: 'Es gibt mehr Bakterienzellen in deinem Körper als menschliche Zellen',  options: ['Wahr', 'Falsch'] }, correct_id: 0, time_limit: 1},
{ data: { text: 'Die Chinesische Mauer kann mit bloßem Auge aus dem Weltraum gesehen werden',  options: ['Wahr', 'Falsch'] }, correct_id: 1, time_limit: 1},
{ data: { text: 'Ein Elefant kann nicht springen',  options: ['Wahr', 'Falsch'] }, correct_id: 0, time_limit: 1},
{ data: { text: 'Der Nil ist schon einmal komplett eingefroren',  options: ['Wahr', 'Falsch'] }, correct_id: 0, time_limit: 1},
{ data: { text: 'Eine Raupe hat etwa gleich viele Muskeln wie ein Mensch',  options: ['Wahr', 'Falsch'] }, correct_id: 1, time_limit: 1},
{ data: { text: 'Geht nicht, gibts nicht.',  options: ['Praktiker', 'Toyota', 'ProMarkt', 'Red Bull'] }, correct_id: 0, time_limit: 1},
{ data: { text: 'In Bayern daheim. In der Welt zu Hause.',  options: ['Paulaner', 'Erdinger', 'Hacker-Pschorr', 'Löwenbräu'] }, correct_id: 1, time_limit: 1},
{ data: { text: 'Abschalten können Sie woanders.',  options: ['ZDF', 'RTL', 'VOX', 'DMAX'] }, correct_id: 0, time_limit: 1},
{ data: { text: 'Knackiger Spaß im Glas.',  options: ['Malibu', 'Berentzen', 'Deutschländer', 'Sierra'] }, correct_id: 1, time_limit: 1},
{ data: { text: 'Wir führen Gutes im Schilde.',  options: ['Deutsche Bank', 'Nestle', 'HUK Coburg', 'Veltins'] }, correct_id: 3, time_limit: 1},
{ data: { text: 'Wieviele Jahre hat Hörby im Verein Fußball gespielt?',  options: ['8', '9', '10', '11'] }, correct_id: 0, time_limit: 1},
{ data: { text: 'Welche ist Hörbys absolute Lieblingsfitnessübung?',  options: ['Liegestützen', 'Sit-Ups', 'Klimmzüge', 'Kniebeugen'] }, correct_id: 2, time_limit: 1},
{ data: { text: 'Was ist Hörbys Lieblingsfastfood?',  options: ['Pizza', 'Burger', 'Süßkartoffelpommes', 'Döner'] }, correct_id: 3, time_limit: 1},
{ data: { text: 'Was hat Hörby noch nie gemacht?',  options: ['Shisha rauchen',  'Zigarre rauchen', 'Vapen', 'Zigarette rauchen'] }, correct_id: 3, time_limit: 1},
{ data: { text: 'Welches dieser Lebewesen kann Hörby am besten ausstehen?',  options: ['Pferd', 'Katze', 'Wespe', 'Kuh'] }, correct_id: 3, time_limit: 1},
{ data: { text: 'Welche Mannschaft der Bundesliga verwendet keine Torhymne?',  options: ['Paderborn', 'Union Berlin', 'Düsseldorf', 'Leverkusen'] }, correct_id: 1, time_limit: 1},
{ data: { text: 'In welchem Fach hatte ich die schlechteste (schriftliche) Note meiner Schullaufbahn?',  options: ['Sport', 'Französisch', 'Deutsch', 'Mathe'] }, correct_id: 3, time_limit: 1},
{ data: { text: 'In welchem Stadion habe ich noch kein Fußballspiel live gesehen?',  options: ['Stuttgart', 'Kiel', 'Braunschweig', 'Dortmund'] }, correct_id: 1, time_limit: 1},
{ data: { text: 'Durch was habe ich mir in meiner Kindheit keine Narbe zugezogen?', image: 'BilderQuiz/QuizNarben.jpg', options: ['Einmachglas', 'Fahrradpedal', 'Blumentopf', 'Legostein']}, correct_id: 1, time_limit: 1 },
{ data: { text: 'Vor wie vielen Monaten habe ich mir meinen Bart das letzte mal komplett abrasiert?', image: 'BilderQuiz/QuizBart.jpg', options: []}, correct_id: 27, time_limit: 1 },
{ data: { text: 'Wie viele Horrorfilme habe ich in den letzten 1,5 Jahren angeschaut?', image: 'BilderQuiz/QuizTheShining.jpg', options: []}, correct_id: 71, time_limit: 1 },
{ data: { text: 'Was sind die Lyrics der ersten Zeile?', youtube: 'https://www.youtube.com/embed/S0Q0fcAT36s',  options: ['An icy mist in the frozen grave', 'And I am fierce in a powerful grasp', 'Another beast in a belted group', 'An iron fist in a velvet glove'] }, correct_id: 3, time_limit: 1},
{ data: { text: 'Wo fand das bisher weltgrößte Bierpong-Turnier statt?',  options: ['Prag', 'London', 'Las Vegas', 'Köln'] }, correct_id: 2, time_limit: 1},
{ data: { text: 'Wie hoch ist das Preisgeld für das erstplatzierte Team bei diesem Turnier (in $)?',  options: [] }, correct_id: 12500, time_limit: 1},
{ data: { text: 'Welche Regel gibt es laut European Series of Beer Pong (ESOBP) in einem Turnier nicht?',  options: ['Ein Bounce Shot zählt als ein Becher', 'Die Becher müssen bei 6,3 und einem Becher neu angeordnet werden', 'Der Ball darf im Becher nicht mehr berührt werden', 'Ein Wurf in den eigenen Becher wird wiederholt'] }, correct_id: 3, time_limit: 1},
{ data: { text: 'Wie lang ist ein offizieller Bierpongtisch? [cm]',image: 'BilderQuiz/QuizTisch.jpg',  options: ['192', '216', '232', '244'] }, correct_id: 3, time_limit: 1},
{ data: { text: 'Aus welchem Jahr stammt das älteste bekannte Bild auf dem Bierpong gespielt wird?',  options: ['1968', '1979', '1992', '2001'] }, correct_id: 0, time_limit: 1},
{ data: { text: 'Wieviel ist dieses Outfit wert?', image: 'BilderQuiz/WIDOW1.jpg', options: []}, correct_id: 557, time_limit: 1 },
{ data: { text: 'Wieviel ist dieses Outfit wert?', image: 'BilderQuiz/WIDOW2.jpg', options: []}, correct_id: 5614, time_limit: 1 },
{ data: { text: 'Ordne die Teile dieses Outfits von billigsten zum teuersten von links nach rechts',image: 'BilderQuiz/WIDOW2.jpg',  options: ['Schuhe',  'Sonnenbrille', 'Schal', 'Handtasche'], order: [2, 1, 0, 3 ] }, correct_id: 0, time_limit: 1} ,
{ data: { text: 'Wieviel ist dieses Outfit wert?', image: 'BilderQuiz/WIDOW3.jpg', options: []}, correct_id: 30380, time_limit: 1 },
{ data: { text: 'Ordne die Teile dieses Outfits von billigsten zum teuersten von links nach rechts',image: 'BilderQuiz/WIDOW3.jpg',  options: ['Schuhe',  'Uhr', 'Mantel', 'Tasche'], order: [1, 3, 2, 0 ] }, correct_id: 0, time_limit: 1},
{ data: { text: 'Welches Lied wird in der WG laut im Gang auf Dauerschleife gespielt, um uns zum Arbeiten zu motivieren?',  options: ['Abfahrt', 'Cheri Cheri Lady', 'Schwarze Natascha', 'Cantina Band'] }, correct_id: 1, time_limit: 1},
{ data: { text: 'Wie viele Tage brauchen wir akuell im Schnitt um 1kg Kaffebohnen zu verbrauchen?', image: 'BilderQuiz/QuizKaffee.jpg', options: []}, correct_id: 14, time_limit: 1 },
{ data: { text: 'Seit wievielen Monaten ernähren wir beide uns in der WG fleischlos?',  options: ['1', '2', '3', '4'] }, correct_id: 3, time_limit: 1},
{ data: { text: 'Wie viele Kästen Bier (inkl. Weizen) wurden in der WG bereits getrunken?', image: 'BilderQuiz/QuizBier.jpg', options: []}, correct_id: 18, time_limit: 1 },
{ data: { text: 'Was wird in dieser Grafik abgebildet?', image: 'BilderQuiz/QuizDiagramm.jpg', options: ['WG Ausgaben', 'Alkoholkonsum', 'LoL KD (in DuoQ Spielen)', 'Bierpong-Trefferquoten']}, correct_id: 3, time_limit: 1 },
]